package com.custombond.dto.response;

import com.custombond.pipeline.PipelineStepType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Immediate acknowledgement returned by {@code POST /vendor/issue}.
 *
 * <p>The controller responds with HTTP {@code 202 Accepted} and this payload
 * <strong>before</strong> the pipeline starts executing.  The vendor should store
 * the {@link #requestId} for correlation:
 * <ul>
 *   <li>It can be used to query logs in the {@code CB_General_Log} table.</li>
 *   <li>It is included in the callback payload ({@link VendorPipelineResult}) once
 *       processing completes.</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Immediate acknowledgement that the pipeline request was accepted")
public class VendorIssuanceAcknowledgement {

    /**
     * Unique correlation ID for this issuance request.
     * Generated by the controller as a UUID and used as {@code parentRequestId}
     * in every DXC service call and log entry throughout the pipeline.
     */
    @Schema(description = "UUID correlation ID – use this to track your request", example = "550e8400-e29b-41d4-a716-446655440000")
    private String requestId;

    /**
     * The vendor's own reference number as submitted in the request.
     * Echoed back for the vendor's convenience.
     */
    @Schema(description = "Vendor's request reference echoed back for convenience", example = "REQ-2024-001")
    private String vendorRequestId;

    /**
     * Human-readable status message confirming acceptance.
     * Always {@code "Request accepted. Processing pipeline asynchronously."} for a
     * successful acknowledgement.
     */
    @Schema(description = "Status message", example = "Request accepted. Processing pipeline asynchronously.")
    private String message;

    /**
     * Server timestamp at the moment the request was accepted.
     * Useful for SLA and latency measurement.
     */
    @Schema(description = "UTC timestamp when the request was accepted by the server")
    private LocalDateTime acceptedAt;

    /**
     * The ordered list of pipeline steps that will be executed asynchronously,
     * as interpreted from the vendor's request.
     */
    @Schema(description = "Ordered list of pipeline steps that will be executed")
    private List<PipelineStepType> steps;
}
