package com.custombond.service;

import com.custombond.dto.request.VendorIssuanceRequest;
import com.custombond.dto.response.VendorPipelineResult;
import com.custombond.pipeline.IssuancePipeline;
import com.custombond.pipeline.IssuancePipelineContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.concurrent.CompletableFuture;

/**
 * Asynchronous service that runs the vendor issuance pipeline on a dedicated thread pool.
 *
 * <h2>Execution model</h2>
 * <ol>
 *   <li>The {@link com.custombond.controller.VendorController} receives the vendor's request
 *       and immediately returns an acknowledgement (HTTP 202).</li>
 *   <li>It then calls {@link #runPipeline} which is annotated with
 *       {@code @Async("externalApiExecutor")} so it executes on the thread pool configured
 *       in {@link com.custombond.config.AsyncConfig} (core=5, max=10, queue=100).</li>
 *   <li>The pipeline result is logged and, if a {@code callbackUrl} was provided,
 *       POSTed back to the vendor.</li>
 * </ol>
 *
 * <h2>Thread safety</h2>
 * Each invocation constructs a fresh {@link IssuancePipelineContext}, so concurrent
 * pipeline runs are fully isolated regardless of shared service beans.
 *
 * <h2>Callback notification</h2>
 * If {@link VendorIssuanceRequest#getCallbackUrl()} is non-blank, a best-effort HTTP POST
 * is made to that URL with the {@link VendorPipelineResult} as JSON body.
 * Failure to reach the callback does <em>not</em> affect the pipeline result stored in the
 * application logs.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class VendorPipelineAsyncService {

    private final IssuancePipeline pipeline;
    private final RestTemplate restTemplate;

    /**
     * Runs the vendor's configured pipeline asynchronously.
     *
     * <p>This method is non-blocking from the caller's perspective: it returns a
     * {@link CompletableFuture} immediately and the actual work happens on the
     * {@code externalApiExecutor} thread pool.
     *
     * @param request          the full vendor issuance request
     * @param parentRequestId  the UUID generated by the controller (used as correlation ID)
     * @param fileBytes        raw bytes of the uploaded document; may be {@code null}
     *                         if {@code UPLOAD_DOCUMENT} is not in the pipeline
     * @param fileName         original file name from the multipart upload; may be {@code null}
     * @param contentType      MIME type of the uploaded file; may be {@code null}
     * @return a future that resolves to the pipeline outcome
     */
    @Async("externalApiExecutor")
    public CompletableFuture<VendorPipelineResult> runPipeline(VendorIssuanceRequest request,
                                                               String parentRequestId,
                                                               byte[] fileBytes,
                                                               String fileName,
                                                               String contentType) {
        log.info("[VendorPipeline] Starting – parentRequestId={}, vendorId={}, steps={}",
                parentRequestId, request.getVendorId(), request.getSteps());

        // Build the shared context for this pipeline run
        IssuancePipelineContext context = IssuancePipelineContext.builder()
                .request(request)
                .parentRequestId(parentRequestId)
                .documentBytes(fileBytes)
                .documentFileName(fileName)
                .documentContentType(contentType)
                .build();

        // Execute the pipeline (mutates context in place)
        pipeline.execute(context);

        // Build the result
        VendorPipelineResult result;
        if (context.isSuccessful()) {
            log.info("[VendorPipeline] SUCCESS – parentRequestId={}, policyNo='{}'",
                    parentRequestId, context.getPolicyNo());
            result = VendorPipelineResult.success(
                    parentRequestId,
                    request.getVendorId(),
                    context.getPolicyNo());
        } else {
            log.error("[VendorPipeline] FAILURE – parentRequestId={}, failedStep='{}', reason='{}'",
                    parentRequestId, context.getFailedStep(), context.getFailureMessage());
            result = VendorPipelineResult.failure(
                    parentRequestId,
                    request.getVendorId(),
                    context.getFailedStep(),
                    context.getFailureMessage());
        }

        // Notify vendor via webhook if callbackUrl was provided
        if (request.getCallbackUrl() != null && !request.getCallbackUrl().isBlank()) {
            notifyVendor(request.getCallbackUrl(), result, parentRequestId);
        }

        return CompletableFuture.completedFuture(result);
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    /**
     * Best-effort HTTP POST of the pipeline result to the vendor's callback URL.
     * Errors are logged but do not propagate – a failed callback never affects
     * the pipeline outcome.
     *
     * @param callbackUrl URL to POST to
     * @param result      the pipeline outcome payload
     * @param parentId    correlation ID for log context
     */
    private void notifyVendor(String callbackUrl,
                              VendorPipelineResult result,
                              String parentId) {
        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            HttpEntity<VendorPipelineResult> entity = new HttpEntity<>(result, headers);
            restTemplate.postForEntity(callbackUrl, entity, String.class);
            log.info("[VendorPipeline] Callback delivered – parentRequestId={}, url={}",
                    parentId, callbackUrl);
        } catch (Exception e) {
            log.warn("[VendorPipeline] Callback failed (best-effort) – parentRequestId={}, url={}, error={}",
                    parentId, callbackUrl, e.getMessage());
        }
    }
}
