package com.custombond.pipeline;

import com.custombond.dto.request.NafezaIssuanceRequest;
import com.custombond.dto.request.VendorIssuanceRequest;
import com.custombond.dto.response.BlackListResponse;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * Mutable context object that is passed through every step of the vendor issuance pipeline.
 *
 * <p><strong>Lifecycle:</strong>
 * <ol>
 *   <li>Created by {@link com.custombond.service.VendorPipelineAsyncService} before the pipeline starts,
 *       initialised with the original {@link VendorIssuanceRequest} and optional file bytes.</li>
 *   <li>Passed sequentially to each {@link PipelineStep#execute(IssuancePipelineContext)}.</li>
 *   <li>Inspected after the pipeline completes to build the
 *       {@link com.custombond.dto.response.VendorPipelineResult}.</li>
 * </ol>
 *
 * <p><strong>Step output conventions:</strong>
 * <ul>
 *   <li>{@code policyNo} / {@code policyKey} – written by {@code QuotePreparationStep},
 *       read by {@code UploadDocumentStep}, {@code IssueQuoteStep}, and {@code IssuePolicyStep}.</li>
 *   <li>{@code blackListResult} – written by {@code CheckBlackListStep}.</li>
 * </ul>
 */
@Getter
@Setter
@Builder
public class IssuancePipelineContext {

    // -----------------------------------------------------------------------
    // Immutable inputs (set once at construction time)
    // -----------------------------------------------------------------------

    /** The original vendor request received by the controller. Never null. */
    private final VendorIssuanceRequest request;

    /**
     * Raw bytes of the document file uploaded by the vendor.
     * {@code null} when the vendor did not include a file part (i.e. {@code UPLOAD_DOCUMENT}
     * is not in the steps list).
     */
    private final byte[] documentBytes;

    /**
     * Original file name from the multipart upload, e.g. {@code "contract.pdf"}.
     * {@code null} when no file was uploaded.
     */
    private final String documentFileName;

    /**
     * MIME content-type of the uploaded file, e.g. {@code "application/pdf"}.
     * {@code null} when no file was uploaded.
     */
    private final String documentContentType;

    /**
     * UUID generated by the controller at the moment the vendor's request was received.
     * Used as the correlation / parent-request-id across all service calls and log entries.
     */
    private final String parentRequestId;

    // -----------------------------------------------------------------------
    // Mutable step outputs (populated as steps execute)
    // -----------------------------------------------------------------------

    /**
     * Policy number returned by the Quote Preparation step.
     * Read by {@code IssueQuoteStep} and {@code IssuePolicyStep}.
     * Falls back to {@code VendorIssuanceRequest.policyNo} when Quote Preparation
     * is not included in the pipeline.
     */
    private String policyNo;

    /**
     * Policy key (instance key) returned by the Quote Preparation step.
     * Used as {@code instnceKey} in the Upload Document step when not supplied explicitly.
     */
    private Long policyKey;

    /**
     * Full response body from the black-list check.
     * Available to subsequent steps if they need contact or stakeholder details.
     * {@code contactKey} inside this response is used by {@code NafezaQuotePreparationStep}
     * as the resolved {@code insured} value.
     */
    private BlackListResponse blackListResult;

    /**
     * DXC contact key resolved from the black-list check and used as the {@code insured}
     * field in the NAFEZA quote preparation request.
     * Written by {@code NafezaQuotePreparationStep}.
     */
    private Long resolvedInsured;

    /**
     * The original NAFEZA issuance request received by the controller.
     * {@code null} for standard vendor flows; populated only when the NAFEZA
     * endpoint ({@code POST /vendor/issue/nafeza}) is used.
     * NAFEZA-specific steps ({@link PipelineStepType#NAFEZA_QUOTE_PREPARATION},
     * {@link PipelineStepType#NAFEZA_UPLOAD_DOCUMENTS}) read their input from here
     * rather than from {@link #request}.
     */
    private NafezaIssuanceRequest nafezaRequest;

    // -----------------------------------------------------------------------
    // Pipeline status
    // -----------------------------------------------------------------------

    /** {@code true} only after all configured steps have executed without error. */
    @Builder.Default
    private boolean successful = false;

    /**
     * Name of the step that caused the pipeline to abort.
     * {@code null} when the pipeline has not yet failed.
     */
    private String failedStep;

    /**
     * Human-readable reason why {@link #failedStep} failed.
     * {@code null} when the pipeline has not yet failed.
     */
    private String failureMessage;

    // -----------------------------------------------------------------------
    // Helper
    // -----------------------------------------------------------------------

    /**
     * Marks the pipeline as failed, recording the responsible step and reason.
     * Once called, {@link #isSuccessful()} returns {@code false} and the
     * pipeline will not proceed to further steps.
     *
     * @param stepName display name of the step that failed
     * @param message  human-readable failure description
     */
    public void markFailed(String stepName, String message) {
        this.failedStep = stepName;
        this.failureMessage = message;
        this.successful = false;
    }

    /**
     * Convenience: resolves the effective policy number.
     * Returns the context value set by Quote Preparation, or falls back to
     * the value the vendor provided directly in the request.
     *
     * @return policy number, or {@code null} if neither source provided one
     */
    public String resolvedPolicyNo() {
        if (policyNo != null) return policyNo;
        if (request != null && request.getPolicyNo() != null) return request.getPolicyNo();
        if (nafezaRequest != null) return nafezaRequest.getPolicyNo();
        return null;
    }
}
